sudo: false
language: ruby
rvm:
  - 2.2.5
before_install: gem install bundler -v 1.12.5

matrix:
  include:
    - rvm: 2.3.3
      env: MONGOID_VERSION=5
    - rvm: 2.3.3
      env: MONGOID_VERSION=6
    - rvm: 2.5.0
      env: MONGOID_VERSION=7
